#!/bin/bash
# 安装备份工具
gongju () {
rpm -qa | grep percona-xtrabackup-80
if [ $? -eq 0 ]
then
    continue
else
    yum -y install percona-xtrabackup-80
    if [ $? -ne 0 ]
    then
        yum install https://repo.percona.com/yum/percona-release-latest.noarch.rpm &> /dev/null
        yum install percona-release-latest.noarch.rpm &> /dev/null
        yum repolist &> /dev/null
        yum -y install percona-xtrabackup-80
        echo "备份工具安装成功"
    fi
fi
}

base () {
read -p "请输入要备份的路径：" basedir
mkdir $basedir
read -p "请输入用户名：" baseuser
read -sp "请输入密码：" password
xtrabackup --defaults-file=/etc/my.cnf --backup --target-dir=$basedir -u"$baseuser" -p'$password' -H localhost -P 3306
if [ $? -eq 0 ]
then
    echo "备份成功"
    read -p "请确认是否准备备份" baseact1
    case in 
    Y|y|yes)
    xtrabackup --prepare --target-dir=$basedir
    *)
    echo "已取消准备"
    ;;
    esac
fi

}
reload () {
read -p "请确认是否开始恢复存档" baseact2
        case $baseact2 in
        Y|y|yes)
        xtrabackup --defaults-file=/etc/my.cnf --copy-back --target-dir=/data/backup/base
        ;;
        *)
        echo "已取消恢复存档"
        ;;
        esac
}
read -p "请选择你要执行的程序" main_act1
case $main_act1 in
1)
base
;;
2)
reload
;;
esac
