#!/bin/bash
WORKDIR='/shell'
for i in $(ls /data/shuihu/userlist/);
do
##用户名称
USERNAME=$(cat /data/shuihu/userlist/${i} | awk -F ":" '{print $1}')
##口令
USERPASSWORD=$(cat /data/shuihu/userlist/${i} | awk -F ":" '{print $2}')
##服务器运行时间
SERVER_TIME=$(date +%F_%T.%N)
#服务器IP
SERVER_IP='192.168.241.23'
#主机名称
SERVER_HOSTNAME=$(hostname)
##服务器发行版本
SERVER_RELEASE=$(cat /etc/redhat-release)
##机器人地址
ROBOT=''
TYPE='Content-Type: application/json'
MSG_TEXT_FILE='/tmp/msg.log'
##消息正文内容文件内容
cat >${MSG_TEXT_FILE}<<eof
标题:添加新用户消息提醒
服务器时间:${SERVER_TIME}
服务器地址:${SERVER_IP}
服务器名称:${SERVER_HOSTNAME}
发行版本:${SERVER_RELEASE}
服务登录名:${USERNAME}
登录口令:${USERPASSWORD}
eof
##json消息体文件路径
MSG_JSON_FILE='/tmp/info.json'
##生成json消息体文件
cat >${MSG_JSON_FILE}<<EOF
{
"msgtype": "text",
"text": {
"content": "$(cat ${MSG_TEXT_FILE})"}}
EOF
##消息推送,正确的丢弃,错误的输出到文件pushinfoerr.log中
curl -s  ${ROBOT} -H "${TYPE}" -d "$(cat ${MSG_JSON_FILE})" >/dev/null  2>${WORKDIR}/pushinfoerr.log
sleep 0.5
done
